
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    config.vm.hostname = "j2.test"

    config.vm.network "private_network", ip: "192.168.150.20",
                                         auto_config: false,
                                         virtualbox__intnet: "network"

    config.vm.provider :libvirt do |lv|
       lv.title = "j2.test"
       lv.cpus = 1
       lv.memory = 512
       lv.management_network_address = '192.169.1.0/24'
    end
  
    config.vm.provision "shell", inline: <<-SHELL
      echo "123" | passwd --stdin root
      sed -i 's/^PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
      systemctl reload sshd

      usermod -aG $(id -u -n) vagrant
    SHELL
  end