
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    config.vm.network "private_network", ip: "172.16.10.101"
    config.vm.hostname = "j2.node"
  
    config.vm.provider :libvirt do |lv|
       lv.title = "j2.node"
       lv.cpus = 2
       lv.memory = 1024
       lv.management_network_address = '192.169.1.0/24'
    end
    
    config.vm.provision "shell", path: "./../install-docker.sh"
  
    config.vm.provision "shell", inline: <<-SHELL
      echo "123" | passwd --stdin root
      sed -i 's/^PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
      systemctl reload sshd

cat >>/etc/hosts<<EOF
172.16.10.100 j2.master
172.16.10.101 j2.node
EOF

    SHELL
  end