version: '3.8'


x-shared_environment: &shared_environment
  J2_MONGO_HOST: j2-mongo
  J2_MONGO_PORT: 27017
  J2_MONGO_DB: j2
  J2_REDIS_HOST: j2-redis
  J2_REDIS_PORT: 6379
  J2_BULL_USER: ${J2_BULL_USER}
  J2_BULL_PWD: ${J2_BULL_PWD}
  
services:
  j2-gateway:
    image: j2-dev
    build:
      dockerfile: ./dev.node18.Dockerfile
      context: .
      args:
        - gUser=${J2_H_NAME}
        - gId=${J2_H_ID}
    environment:
      <<: *shared_environment
    ports:
      - "${J2_BE_PORT}:3000"
    volumes:
      - ../apps/server:/data/apps
    
  j2-redis:
    image: redis:7.0.7-alpine3.17
    environment:
      <<: *shared_environment
    ports:
      - "6379:6379"
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ../conf/redis.dev.conf:/usr/local/etc/redis/redis.conf
      - ../data/redis:/data
        
  j2-mongo:
    image: mongo:6.0.3
    command: mongod --quiet --logpath /dev/null
    environment:
      <<: *shared_environment
    ports:
      - "27017:27017"
    volumes:
      - ../conf/mongod.dev.conf:/etc/mongodb.conf
      - ../data/mongo/log:/var/log/mongodb/
      - ../data/mongo/data:/data/db