version: '3.8'


x-shared_environment: &shared_environment
  J2_MONGO_HOST: j2-mongo
  J2_MONGO_PORT: 27017
  J2_MONGO_DB: j2
  J2_REDIS_HOST: j2-redis
  J2_REDIS_PORT: 6379
  J2_SUPER_USER: ${J2_SUPER_USER}
  J2_SUPER_PWD: ${J2_SUPER_PWD}
  J2_DOCKER_INTERFACE: ${J2_DOCKER_INTERFACE}
  J2_DOCKER_CA: ${J2_DOCKER_CA}
  J2_DOCKER_CLIENT_CERT: ${J2_DOCKER_CLIENT_CERT}
  J2_DOCKER_CLIENT_KEY: ${J2_DOCKER_CLIENT_KEY}
  J2_JWT_REFRESH_SECRET: ${J2_JWT_REFRESH_SECRET}
  J2_JWT_REFRESH_EXPIRED: ${J2_JWT_REFRESH_EXPIRED}
  J2_JWT_ACCESS_SECRET: ${J2_JWT_ACCESS_SECRET}
  J2_JWT_ACCESS_EXPIRED: ${J2_JWT_ACCESS_EXPIRED}
  
services:
  j2-gateway:
    image: j2-dev
    build:
      dockerfile: ./dev.node18.Dockerfile
      context: .
      args:
        - gUser=${J2_H_NAME}
        - gId=${J2_H_ID}
    environment:
      <<: *shared_environment
    ports:
      - "${J2_BE_PORT}:3000"
    volumes:
      - ../apps/server:/data/apps
      - ../keys:/keys
    networks:
      - all
      - docker-swarm
    
  j2-redis:
    image: redis:7.0.7-alpine3.17
    environment:
      <<: *shared_environment
    ports:
      - "6379:6379"
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ../conf/redis.dev.conf:/usr/local/etc/redis/redis.conf
      - ../data/redis:/data
    networks:
      - all

  j2-mongo:
    image: mongo:6.0.3
    command: mongod --quiet --logpath /dev/null
    environment:
      <<: *shared_environment
    ports:
      - "27017:27017"
    volumes:
      - ../conf/mongod.dev.conf:/etc/mongodb.conf
      - ../data/mongo/log:/var/log/mongodb/
      - ../data/mongo/data:/data/db
    networks:
      - all

networks:
  all:
  docker-swarm:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: "${J2_DOCKER_INTERFACE}"
    ipam:
      config:
        - subnet: 172.16.10.0/24
          gateway: 172.16.10.1
          ip_range: 172.16.10.110/28