version: '3.8'


x-shared_environment: &shared_environment
  J2_MONGO_HOST: j2-mongo
  J2_MONGO_PORT: 27017
  J2_MONGO_DB: j2
  J2_REDIS_HOST: j2-redis
  J2_REDIS_PORT: 6379
  J2_SUPER_USER: ${J2_SUPER_USER}
  J2_SUPER_PWD: ${J2_SUPER_PWD}
  J2_DOCKER_INTERFACE: ${J2_DOCKER_INTERFACE}
  J2_JWT_REFRESH_SECRET: ${J2_JWT_REFRESH_SECRET}
  J2_JWT_REFRESH_EXPIRED: ${J2_JWT_REFRESH_EXPIRED}
  J2_JWT_ACCESS_SECRET: ${J2_JWT_ACCESS_SECRET}
  J2_JWT_ACCESS_EXPIRED: ${J2_JWT_ACCESS_EXPIRED}
  J2_SIB_TOKEN: ${J2_SIB_TOKEN}
  J2_SIB_EMAIL: ${J2_SIB_EMAIL}
  J2_VERIFY_LINK: ${J2_VERIFY_LINK}
  
services:
  j2-gateway:
    image: j2-prod-server
    environment:
      <<: *shared_environment
    ports:
      - "${J2_BE_PORT}:3000"
    volumes:
      - /data/img:/data/image
    networks:
      - all
    
  j2-redis:
    image: redis:6.0.20-alpine3.18
    environment:
      <<: *shared_environment
    ports:
      - "6379:6379"
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - /data/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - /data/data/redis:/data
    networks:
      - all

  j2-mongo:
    image: mongo:6.0.3
    command: mongod --quiet --logpath /dev/null
    environment:
      <<: *shared_environment
    ports:
      - "27017:27017"
    volumes:
      - /data/conf/mongod.conf:/etc/mongodb.conf
      - /data/data/mongo/log:/var/log/mongodb/
      - /data/data/mongo/data:/data/db
    networks:
      - all

networks:
  all: