version: '3.8'

services:
  frontend:
    image: nginx:1.25.1-alpine3.17
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /data/conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - /data/ssl:/data/ssl
    network_mode: bridge